CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(250) NOT NULL,
    DATA DATE NOT NULL,
    FOTO VARCHAR(250) NOT NULL,
    BIOGRAFIA VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS MUSICA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(250) NOT NULL,
    DURACAO VARCHAR(10) NOT NULL,
    CAPA VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTISTA_MUSICA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ARTISTA_ID INTEGER,
    FK_MUSICA_ID INTEGER,
	FOREIGN KEY (FK_ARTISTA_ID) REFERENCES ARTISTA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_MUSICA_ID) REFERENCES MUSICA(ID) ON DELETE CASCADE
);